const fs = require("fs");
const path = require("path");

const root = __dirname;
const sourcePath = path.join(root, "e-mall.openapi.json");
const outputPath = path.join(root, "output.json");

const oid = (example) => ({
  type: "string",
  pattern: "^[a-fA-F0-9]{24}$",
  example: example || "64f000000000000000000001",
});

const dt = (example) => ({
  type: "string",
  format: "date-time",
  example: example || "2026-06-12T10:00:00.000Z",
});

const ref = (name) => ({ $ref: `#/components/schemas/${name}` });
const paramRef = (name) => ({ $ref: `#/components/parameters/${name}` });
const requestRef = (name) => ({ $ref: `#/components/requestBodies/${name}` });
const responseRef = (name) => ({ $ref: `#/components/responses/${name}` });

const schemaResponse = (schemaName, description) => ({
  description,
  content: {
    "application/json": {
      schema: ref(schemaName),
    },
  },
});

const stringResponse = (description, example) => ({
  description,
  content: {
    "application/json": {
      schema: { type: "string", example },
    },
  },
});

const requestBody = (schemaName, description) => ({
  description,
  required: true,
  content: {
    "application/json": {
      schema: ref(schemaName),
    },
  },
});

const envelope = (dataProps, requiredDataKeys = []) => ({
  type: "object",
  required: ["status", "data"],
  properties: {
    status: { type: "string", example: "success" },
    data: {
      type: "object",
      required: requiredDataKeys,
      properties: dataProps,
    },
  },
});

const messageEnvelope = (messageExample) => ({
  type: "object",
  required: ["status", "message"],
  properties: {
    status: { type: "string", example: "success" },
    message: { type: "string", example: messageExample },
  },
});

const tags = [
  {
    name: "Auth",
    description: "Authentication, token issuance, password reset, and email verification flows.",
  },
  {
    name: "Categories",
    description: "Catalog categories and category usage lifecycle operations.",
  },
  {
    name: "Stores",
    description: "Public store discovery and admin-facing store lifecycle operations.",
  },
  {
    name: "Store Management",
    description: "Owner/admin store settings, dashboards, orders, and store-scoped product tools.",
  },
  {
    name: "Store Products",
    description: "Store-scoped product creation and management endpoints.",
  },
  {
    name: "Catalog",
    description: "Public product browsing and product lookup by slug.",
  },
  {
    name: "Cart",
    description: "Authenticated cart management for the current user.",
  },
  {
    name: "Wishlist",
    description: "Authenticated wishlist management for the current user.",
  },
  {
    name: "Addresses",
    description: "Authenticated address book management for the current user.",
  },
  {
    name: "Orders",
    description: "Customer order lifecycle operations and payment initiation.",
  },
  {
    name: "Delivery",
    description: "Fulfillment and admin delivery workflow operations.",
  },
  {
    name: "Payments",
    description: "Payment gateway webhook integration.",
  },
  {
    name: "Notifications",
    description: "Authenticated in-app notification access and mutation.",
  },
];

const components = {
  securitySchemes: {
    BearerAuth: {
      type: "http",
      scheme: "bearer",
      bearerFormat: "JWT",
      description: "JWT access token passed in the Authorization header as Bearer <token>.",
    },
    RefreshTokenCookie: {
      type: "apiKey",
      in: "cookie",
      name: "refreshToken",
      description: "HttpOnly refresh token cookie issued on login/register/refresh and required for refresh/logout.",
    },
  },
  parameters: {
    StoreIdParam: {
      name: "storeId",
      in: "path",
      required: true,
      description: "Store identifier.",
      schema: oid("65f000000000000000000001"),
    },
    ProductIdParam: {
      name: "productId",
      in: "path",
      required: true,
      description: "Product identifier.",
      schema: oid("65f000000000000000000002"),
    },
    CategoryIdParam: {
      name: "categoryId",
      in: "path",
      required: true,
      description: "Category identifier.",
      schema: oid("65f000000000000000000003"),
    },
    OrderIdParam: {
      name: "orderId",
      in: "path",
      required: true,
      description: "Order identifier.",
      schema: oid("65f000000000000000000004"),
    },
    VariantIdParam: {
      name: "variantId",
      in: "path",
      required: true,
      description: "Variant identifier.",
      schema: oid("65f000000000000000000005"),
    },
    AddressIdParam: {
      name: "addressId",
      in: "path",
      required: true,
      description: "Address identifier.",
      schema: oid("65f000000000000000000006"),
    },
    NotificationIdParam: {
      name: "notificationId",
      in: "path",
      required: true,
      description: "Notification identifier.",
      schema: oid("65f000000000000000000007"),
    },
    TokenParam: {
      name: "token",
      in: "path",
      required: true,
      description: "Verification or reset token.",
      schema: { type: "string", minLength: 1, example: "eyJhbGciOiJIUzI1NiIs..." },
    },
    SlugParam: {
      name: "slug",
      in: "path",
      required: true,
      description: "Product slug.",
      schema: { type: "string", minLength: 1, example: "iphone-15-pro-max" },
    },
    PageParam: {
      name: "page",
      in: "query",
      required: false,
      description: "Page number, starting at 1.",
      schema: { type: "integer", minimum: 1, example: 1 },
    },
    LimitParam: {
      name: "limit",
      in: "query",
      required: false,
      description: "Maximum number of items per page.",
      schema: { type: "integer", minimum: 1, maximum: 100, example: 20 },
    },
    SearchParam: {
      name: "search",
      in: "query",
      required: false,
      description: "Free-text search term.",
      schema: { type: "string", example: "apple" },
    },
    ActiveParam: {
      name: "active",
      in: "query",
      required: false,
      description: "Admin-only store activity filter.",
      schema: { type: "boolean", example: true },
    },
    IsActiveParam: {
      name: "isActive",
      in: "query",
      required: false,
      description: "Filter store products by activity.",
      schema: { type: "boolean", example: true },
    },
    StoreQueryParam: {
      name: "storeId",
      in: "query",
      required: false,
      description: "Filter products by a store identifier.",
      schema: oid("65f000000000000000000008"),
    },
    ShopIdParam: {
      name: "shopId",
      in: "query",
      required: false,
      description: "Alternate store identifier accepted by the product search pipeline.",
      schema: oid("65f000000000000000000009"),
    },
    CategoryQueryParam: {
      name: "category",
      in: "query",
      required: false,
      description: "Category identifier or slug.",
      schema: { type: "string", example: "electronics" },
    },
    MinPriceParam: {
      name: "minPrice",
      in: "query",
      required: false,
      description: "Lower price bound.",
      schema: { type: "number", minimum: 0, example: 50 },
    },
    MaxPriceParam: {
      name: "maxPrice",
      in: "query",
      required: false,
      description: "Upper price bound.",
      schema: { type: "number", minimum: 0, example: 5000 },
    },
    SortParam: {
      name: "sort",
      in: "query",
      required: false,
      description: "Product sort order.",
      schema: {
        type: "string",
        enum: ["price-asc", "price-desc", "newest", "best-selling"],
        example: "newest",
      },
    },
    ColorParam: {
      name: "color",
      in: "query",
      required: false,
      description: "Variant color filter. Additional top-level query keys are also treated as attribute filters.",
      schema: { type: "string", example: "black" },
    },
    SizeParam: {
      name: "size",
      in: "query",
      required: false,
      description: "Variant size filter.",
      schema: { type: "string", example: "XL" },
    },
  },
  schemas: {
    ApiMessage: messageEnvelope("Action completed successfully"),
    LogoutMessage: { type: "string", examples: ["Logout successfully", "cookies not found"] },
    ErrorResponse: {
      type: "object",
      required: ["status", "message"],
      properties: {
        status: { type: "string", example: "error" },
        message: { type: "string", example: "Something went very wrong!" },
        error: { type: "object", additionalProperties: true },
        stack: { type: "string" },
      },
    },
    AuthRole: {
      type: "string",
      enum: ["admin", "user", "owner", "accounting", "fulfillment"],
      example: "user",
    },
    User: {
      type: "object",
      required: ["_id", "email", "name", "role", "isActive", "isEmailVerified", "isPhoneVerified", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000001001"),
        email: { type: "string", format: "email", example: "customer@example.com" },
        name: { type: "string", example: "Amina Hassan" },
        phoneNumber: { type: "string", example: "01012345678" },
        role: ref("AuthRole"),
        isActive: { type: "boolean", example: true },
        isEmailVerified: { type: "boolean", example: true },
        isPhoneVerified: { type: "boolean", example: false },
        deletedAt: { type: ["string", "null"], format: "date-time", example: null },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    AuthUser: {
      type: "object",
      required: ["id", "name", "email"],
      properties: {
        id: oid("65f000000000000000001002"),
        name: { type: "string", example: "Amina Hassan" },
        email: { type: "string", format: "email", example: "customer@example.com" },
        phoneNumber: { type: "string", example: "01012345678" },
      },
    },
    LoginSession: {
      type: "object",
      required: ["_id", "userId", "refreshToken", "expiresAt", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000001003"),
        userId: oid("65f000000000000000001004"),
        refreshToken: { type: "string", example: "hashed-refresh-token" },
        ip: { type: ["string", "null"], example: "127.0.0.1" },
        userAgent: { type: ["string", "null"], example: "Mozilla/5.0" },
        lastUsedAt: { type: ["string", "null"], format: "date-time", example: null },
        revokedAt: { type: ["string", "null"], format: "date-time", example: null },
        expiresAt: dt("2026-07-12T09:00:00.000Z"),
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    VerifyTokenType: {
      type: "string",
      enum: ["verify", "reset"],
      example: "verify",
    },
    VerifyTokens: {
      type: "object",
      required: ["_id", "token", "type", "expiresAt", "used", "userId", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000001005"),
        token: { type: "string", example: "vfy_8a9d2f..." },
        type: ref("VerifyTokenType"),
        expiresAt: dt("2026-06-12T10:00:00.000Z"),
        used: { type: "boolean", example: false },
        userId: oid("65f000000000000000001006"),
        verifiedAt: { type: ["string", "null"], format: "date-time", example: null },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    CategoryRef: {
      type: "object",
      required: ["_id", "name", "slug"],
      properties: {
        _id: oid("65f000000000000000002001"),
        name: { type: "string", example: "Electronics" },
        slug: { type: "string", example: "electronics" },
      },
    },
    Category: {
      type: "object",
      required: ["_id", "name", "slug", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000002002"),
        name: { type: "string", example: "Electronics" },
        slug: { type: "string", example: "electronics" },
        parent: {
          oneOf: [{ $ref: "#/components/schemas/CategoryRef" }, { type: "null" }],
          example: null,
        },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    CategoryUsage: {
      type: "object",
      required: ["productCount", "storeCount", "isInUse"],
      properties: {
        productCount: { type: "integer", example: 12 },
        storeCount: { type: "integer", example: 3 },
        isInUse: { type: "boolean", example: true },
      },
    },
    StoreRef: {
      type: "object",
      required: ["_id", "name"],
      properties: {
        _id: oid("65f000000000000000003001"),
        name: { type: "string", example: "Downtown Market" },
        logo: { type: "string", example: "https://cdn.example.com/store/logo.png" },
      },
    },
    Store: {
      type: "object",
      required: ["_id", "name", "isActive", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000003000"),
        name: { type: "string", example: "Downtown Market" },
        logo: { type: "string", example: "https://cdn.example.com/store/logo.png" },
        category: {
          oneOf: [{ $ref: "#/components/schemas/CategoryRef" }, { type: "null" }],
          example: null,
        },
        owner: {
          oneOf: [{ $ref: "#/components/schemas/UserRef" }, { type: "null" }],
          example: null,
        },
        authorizedBrand: { type: "string", example: "Apple" },
        isActive: { type: "boolean", example: true },
        openingTime: { type: "string", example: "08:00" },
        closingTime: { type: "string", example: "22:00" },
        deletedAt: { type: ["string", "null"], format: "date-time", example: null },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    UserRef: {
      type: "object",
      required: ["_id", "name", "email"],
      properties: {
        _id: oid("65f000000000000000003002"),
        name: { type: "string", example: "Amina Hassan" },
        email: { type: "string", format: "email", example: "owner@example.com" },
      },
    },
    ProductAttribute: {
      type: "object",
      required: ["name", "value"],
      properties: {
        name: { type: "string", example: "color" },
        value: { type: "string", example: "black" },
      },
    },
    ProductVariant: {
      type: "object",
      required: ["_id", "sku", "price", "isDefault"],
      properties: {
        _id: oid("65f000000000000000003101"),
        sku: { type: "string", example: "IPH15PM-BLK-256" },
        price: { type: "number", minimum: 0, example: 42999 },
        salePrice: { type: "number", minimum: 0, example: 39999 },
        saleStartAt: { type: "string", format: "date-time", example: "2026-06-12T00:00:00.000Z" },
        saleEndAt: { type: "string", format: "date-time", example: "2026-07-12T00:00:00.000Z" },
        imageUrl: { type: "string", example: "https://cdn.example.com/products/iphone-15-pro-max-black.png" },
        images: { type: "array", items: { type: "string" }, example: ["https://cdn.example.com/products/iphone-15-pro-max-1.png"] },
        isDefault: { type: "boolean", example: true },
        attributes: {
          type: "array",
          items: ref("ProductAttribute"),
        },
        currentPrice: { type: "number", example: 39999 },
        isSaleActive: { type: "boolean", example: true },
      },
    },
    ProductRef: {
      type: "object",
      required: ["_id", "name", "slug"],
      properties: {
        _id: oid("65f000000000000000003102"),
        name: { type: "string", example: "iPhone 15 Pro Max" },
        slug: { type: "string", example: "iphone-15-pro-max" },
        images: { type: "array", items: { type: "string" }, example: ["https://cdn.example.com/products/iphone.png"] },
      },
    },
    Product: {
      type: "object",
      required: ["_id", "name", "slug", "category", "store", "isActive", "salesCount", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000003103"),
        name: { type: "string", example: "iPhone 15 Pro Max" },
        slug: { type: "string", example: "iphone-15-pro-max" },
        description: { type: "string", example: "Flagship smartphone." },
        brand: { type: "string", example: "Apple" },
        category: {
          oneOf: [{ $ref: "#/components/schemas/CategoryRef" }, { type: "null" }],
          example: null,
        },
        store: {
          oneOf: [{ $ref: "#/components/schemas/StoreRef" }, { type: "null" }],
          example: null,
        },
        basePrice: { type: "number", minimum: 0, example: 44999 },
        variants: { type: "array", items: ref("ProductVariant") },
        defaultVariantId: { oneOf: [{ type: "string", pattern: "^[a-fA-F0-9]{24}$" }, { type: "null" }], example: null },
        tags: { type: "array", items: { type: "string" }, example: ["smartphone", "flagship"] },
        mainVariant: {
          oneOf: [{ $ref: "#/components/schemas/ProductVariant" }, { type: "null" }],
          example: null,
        },
        matchedCount: { type: "integer", example: 1 },
        isActive: { type: "boolean", example: true },
        salesCount: { type: "integer", example: 128 },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    CartItem: {
      type: "object",
      required: ["product", "store", "quantity"],
      properties: {
        variantId: oid("65f000000000000000004001"),
        product: {
          oneOf: [{ $ref: "#/components/schemas/ProductRef" }, { type: "null" }],
          example: null,
        },
        store: {
          oneOf: [{ $ref: "#/components/schemas/StoreRef" }, { type: "null" }],
          example: null,
        },
        quantity: { type: "integer", minimum: 1, example: 2 },
        unitPrice: { oneOf: [{ type: "number" }, { type: "null" }], example: 39999 },
        totalPrice: { type: "number", example: 79998 },
        isPriceAvailable: { type: "boolean", example: true },
      },
    },
    Cart: {
      type: "object",
      required: ["_id", "items", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000004002"),
        user: {
          oneOf: [{ $ref: "#/components/schemas/UserRef" }, { type: "null" }],
          example: null,
        },
        items: {
          type: "array",
          items: ref("CartItem"),
        },
        totalPrice: { type: "number", example: 79998 },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    WishListItem: {
      type: "object",
      required: ["product"],
      properties: {
        variantId: oid("65f000000000000000004003"),
        product: {
          oneOf: [{ $ref: "#/components/schemas/ProductRef" }, { type: "null" }],
          example: null,
        },
        store: {
          oneOf: [{ $ref: "#/components/schemas/StoreRef" }, { type: "null" }],
          example: null,
        },
      },
    },
    WishList: {
      type: "object",
      required: ["_id", "items", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000004004"),
        user: {
          oneOf: [{ $ref: "#/components/schemas/UserRef" }, { type: "null" }],
          example: null,
        },
        items: {
          type: "array",
          items: ref("WishListItem"),
        },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    Address: {
      type: "object",
      required: ["_id", "street", "city", "distanceMark", "phone", "isDefault", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000005001"),
        street: { type: "string", example: "12 Tahrir Street" },
        city: { type: "string", example: "Cairo" },
        distanceMark: { type: "string", example: "Near the blue pharmacy" },
        phone: { type: "string", example: "01012345678" },
        notes: { type: "string", example: "Ring the bell twice." },
        isDefault: { type: "boolean", example: true },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    BuyerAddressSnapshot: {
      type: "object",
      required: ["street", "city", "distanceMark"],
      properties: {
        street: { type: "string", example: "12 Tahrir Street" },
        city: { type: "string", example: "Cairo" },
        distanceMark: { type: "string", example: "Near the blue pharmacy" },
      },
    },
    BuyerSnapshot: {
      type: "object",
      required: ["name", "phone", "address"],
      properties: {
        name: { type: "string", example: "Amina Hassan" },
        phone: { type: "string", example: "01012345678" },
        address: ref("BuyerAddressSnapshot"),
      },
    },
    OrderStoreItem: {
      type: "object",
      required: ["_id", "productId", "variantId", "productNameSnapshot", "variantSnapshot", "quantity", "unitPrice", "totalPrice"],
      properties: {
        _id: oid("65f000000000000000006001"),
        productId: oid("65f000000000000000006002"),
        variantId: oid("65f000000000000000006003"),
        productNameSnapshot: { type: "string", example: "iPhone 15 Pro Max" },
        variantSnapshot: { type: "string", example: "color: black / storage: 256GB" },
        quantity: { type: "integer", minimum: 1, example: 2 },
        unitPrice: { type: "number", minimum: 0, example: 39999 },
        totalPrice: { type: "number", minimum: 0, example: 79998 },
      },
    },
    OrderStore: {
      type: "object",
      required: ["_id", "storeId", "storeNameSnapshot", "status", "items", "subtotal"],
      properties: {
        _id: oid("65f000000000000000006004"),
        storeId: oid("65f000000000000000006005"),
        storeNameSnapshot: { type: "string", example: "Downtown Market" },
        status: {
          type: "string",
          enum: ["pending", "preparing", "ready", "rejected"],
          example: "pending",
        },
        rejectionReason: { type: "string", example: "Some items are not available." },
        items: {
          type: "array",
          items: ref("OrderStoreItem"),
        },
        subtotal: { type: "number", minimum: 0, example: 79998 },
      },
    },
    MissingOrderItem: {
      type: "object",
      required: ["_id", "storeId", "orderItemId", "reason"],
      properties: {
        _id: oid("65f000000000000000006006"),
        storeId: oid("65f000000000000000006007"),
        orderItemId: oid("65f000000000000000006008"),
        itemId: oid("65f000000000000000006009"),
        reason: { type: "string", example: "Variant is out of stock" },
      },
    },
    OrderPaymentMethod: {
      type: "string",
      enum: ["cod", "online"],
      example: "online",
    },
    OrderPaymentStatus: {
      type: "string",
      enum: ["pending", "paid", "failed", "refunded"],
      example: "pending",
    },
    OrderDeliveryStatus: {
      type: "string",
      enum: ["none", "assigned", "collecting", "on_the_way", "delivered"],
      example: "assigned",
    },
    OrderStatus: {
      type: "string",
      enum: [
        "pending",
        "waiting_store_acceptance",
        "waiting_customer_decision",
        "waiting_payment",
        "ready_for_delivery",
        "out_for_delivery",
        "delivered",
        "cancelled",
      ],
      example: "pending",
    },
    OrderPayment: {
      type: "object",
      required: ["method", "status"],
      properties: {
        method: ref("OrderPaymentMethod"),
        status: ref("OrderPaymentStatus"),
      },
    },
    OrderDelivery: {
      type: "object",
      required: ["status"],
      properties: {
        riderId: oid("65f000000000000000006010"),
        status: ref("OrderDeliveryStatus"),
      },
    },
    OrderTotals: {
      type: "object",
      required: ["itemsTotal", "deliveryFee", "grandTotal"],
      properties: {
        itemsTotal: { type: "number", minimum: 0, example: 79998 },
        deliveryFee: { type: "number", minimum: 0, example: 50 },
        grandTotal: { type: "number", minimum: 0, example: 80048 },
      },
    },
    Order: {
      type: "object",
      required: ["_id", "buyerSnapshot", "stores", "missingItems", "orderStatus", "payment", "delivery", "totals", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000006011"),
        buyerSnapshot: ref("BuyerSnapshot"),
        stores: {
          type: "array",
          items: ref("OrderStore"),
        },
        missingItems: {
          type: "array",
          items: ref("MissingOrderItem"),
        },
        orderStatus: ref("OrderStatus"),
        payment: ref("OrderPayment"),
        delivery: ref("OrderDelivery"),
        totals: ref("OrderTotals"),
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    StoreOrder: {
      type: "object",
      required: ["_id", "stores", "missingItems", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000006012"),
        stores: {
          type: "array",
          items: ref("OrderStore"),
        },
        missingItems: {
          type: "array",
          items: ref("MissingOrderItem"),
        },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    PaymentIntent: {
      type: "object",
      required: ["provider", "id", "clientSecret", "amount", "currency", "status"],
      properties: {
        provider: { type: "string", example: "stub" },
        id: { type: "string", example: "pi_65f000000000000000006011_1718188800000" },
        clientSecret: { type: "string", example: "pi_secret_65f000000000000000006011" },
        amount: { type: "number", example: 80048 },
        currency: { type: "string", example: "EGP" },
        status: { type: "string", example: "requires_confirmation" },
      },
    },
    OrderPaymentPayload: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Payment intent created successfully" },
        data: {
          type: "object",
          required: ["order", "paymentIntent"],
          properties: {
            order: ref("Order"),
            paymentIntent: ref("PaymentIntent"),
          },
        },
      },
    },
    DashboardProductStat: {
      type: "object",
      required: ["product", "count"],
      properties: {
        product: {
          oneOf: [{ $ref: "#/components/schemas/ProductRef" }, { type: "null" }],
          example: null,
        },
        count: { type: "integer", example: 8 },
      },
    },
    DashboardBestSellerStat: {
      type: "object",
      required: ["product", "sold"],
      properties: {
        product: {
          oneOf: [{ $ref: "#/components/schemas/ProductRef" }, { type: "null" }],
          example: null,
        },
        sold: { type: "integer", example: 22 },
      },
    },
    StoreDashboardStats: {
      type: "object",
      required: ["totalProducts", "productsInCarts", "productsInWishlists"],
      properties: {
        totalProducts: { type: "integer", example: 17 },
        productsInCarts: {
          type: "array",
          items: ref("DashboardProductStat"),
        },
        productsInWishlists: {
          type: "array",
          items: ref("DashboardProductStat"),
        },
        bestSelling: {
          type: "array",
          items: ref("DashboardBestSellerStat"),
        },
      },
    },
    NotificationEvent: {
      type: "string",
      enum: [
        "order_created",
        "order_ready",
        "order_cancelled",
        "missing_items",
        "payment_required",
        "payment_success",
        "payment_failed",
        "delivery_assigned",
        "out_for_delivery",
        "order_delivered",
      ],
      example: "order_created",
    },
    NotificationEntityType: {
      type: "string",
      enum: ["order", "payment", "delivery"],
      example: "order",
    },
    Notification: {
      type: "object",
      required: ["_id", "recipientId", "title", "message", "type", "entityType", "entityId", "isRead", "createdAt", "updatedAt"],
      properties: {
        _id: oid("65f000000000000000007001"),
        recipientId: oid("65f000000000000000007002"),
        title: { type: "string", example: "Order ready" },
        message: { type: "string", example: "Your order is ready for delivery." },
        type: ref("NotificationEvent"),
        entityType: ref("NotificationEntityType"),
        entityId: oid("65f000000000000000007003"),
        isRead: { type: "boolean", example: false },
        readAt: { type: ["string", "null"], format: "date-time", example: null },
        createdAt: dt("2026-06-12T09:00:00.000Z"),
        updatedAt: dt("2026-06-12T09:00:00.000Z"),
      },
    },
    AuthSessionResponse: envelope(
      {
        user: ref("AuthUser"),
      },
      ["user"],
    ),
    AuthSessionData: {
      type: "object",
      required: ["user"],
      properties: {
        user: ref("AuthUser"),
      },
    },
    AuthSessionEnvelope: {
      type: "object",
      required: ["status", "token", "data"],
      properties: {
        status: { type: "string", example: "success" },
        token: { type: "string", example: "eyJhbGciOiJIUzI1NiIs..." },
        data: ref("AuthSessionData"),
      },
    },
    AuthMessageResponse: {
      type: "object",
      required: ["message"],
      properties: {
        message: { type: "string", example: "Password reset email sent successfully" },
      },
    },
    LogoutMessageResponse: { type: "string", example: "Logout successfully" },
    CategoryListResponse: envelope(
      {
        categories: { type: "array", items: ref("Category") },
        total: { type: "integer", example: 2 },
      },
      ["categories", "total"],
    ),
    CategoryItemResponse: envelope({ category: ref("Category") }, ["category"]),
    CategoryUsageResponse: envelope(
      {
        productCount: { type: "integer", example: 12 },
        storeCount: { type: "integer", example: 3 },
        isInUse: { type: "boolean", example: true },
      },
      ["productCount", "storeCount", "isInUse"],
    ),
    CategoryReplaceResult: {
      type: "object",
      required: ["oldCategoryId", "newCategoryId", "oldCategoryName", "newCategoryName"],
      properties: {
        oldCategoryId: oid("65f000000000000000002010"),
        newCategoryId: oid("65f000000000000000002011"),
        oldCategoryName: { type: "string", example: "Phones" },
        newCategoryName: { type: "string", example: "Smartphones" },
      },
    },
    CategoryReplaceResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: {
          type: "string",
          example:
            "Category replacement processed. Please note: Products and Stores using the old category need to be migrated manually or via a migration script.",
        },
        data: {
          type: "object",
          required: ["result"],
          properties: {
            result: ref("CategoryReplaceResult"),
          },
        },
      },
    },
    StoreListResponse: envelope(
      {
        stores: { type: "array", items: ref("Store") },
        total: { type: "integer", example: 5 },
      },
      ["stores", "total"],
    ),
    StoreItemResponse: envelope({ store: ref("Store") }, ["store"]),
    StoreActionResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Store updated successfully" },
        data: {
          type: "object",
          required: ["store"],
          properties: {
            store: ref("Store"),
          },
        },
      },
    },
    StoreDashboardResponse: envelope({ ...{ stats: ref("StoreDashboardStats") } }, ["stats"]),
    StoreDashboardRawResponse: {
      type: "object",
      required: ["status", "data"],
      properties: {
        status: { type: "string", example: "success" },
        data: ref("StoreDashboardStats"),
      },
    },
    StoreProductListResponse: envelope(
      {
        products: { type: "array", items: ref("Product") },
        total: { type: "integer", example: 24 },
        page: { type: "integer", example: 1 },
        limit: { type: "integer", example: 24 },
      },
      ["products", "total", "page", "limit"],
    ),
    StoreProductItemResponse: envelope({ product: ref("Product") }, ["product"]),
    CartResponse: {
      type: "object",
      required: ["status", "data"],
      properties: {
        status: { type: "string", example: "success" },
        data: ref("Cart"),
      },
    },
    CartActionResponse: messageEnvelope("Item added to cart successfully"),
    WishlistResponse: {
      type: "object",
      required: ["status", "data"],
      properties: {
        status: { type: "string", example: "success" },
        data: ref("WishList"),
      },
    },
    WishlistActionResponse: messageEnvelope("Item added to wishlist successfully"),
    AddressListResponse: envelope(
      {
        addresses: { type: "array", items: ref("Address") },
        total: { type: "integer", example: 2 },
      },
      ["addresses", "total"],
    ),
    AddressItemResponse: envelope({ address: ref("Address") }, ["address"]),
    AddressActionResponse: envelope({ address: ref("Address") }, ["address"]),
    OrderListResponse: envelope(
      {
        orders: { type: "array", items: ref("Order") },
        total: { type: "integer", example: 2 },
      },
      ["orders", "total"],
    ),
    OrderItemResponse: envelope({ order: ref("Order") }, ["order"]),
    OrderActionResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Order created successfully" },
        data: {
          type: "object",
          required: ["order"],
          properties: {
            order: ref("Order"),
          },
        },
      },
    },
    StoreOrderListResponse: envelope(
      {
        orders: { type: "array", items: ref("StoreOrder") },
        total: { type: "integer", example: 2 },
      },
      ["orders", "total"],
    ),
    StoreOrderItemResponse: envelope({ order: ref("StoreOrder") }, ["order"]),
    StoreOrderActionResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Order updated successfully" },
        data: {
          type: "object",
          required: ["order"],
          properties: {
            order: ref("StoreOrder"),
          },
        },
      },
    },
    DeliveryOrderListResponse: envelope(
      {
        orders: { type: "array", items: ref("Order") },
        total: { type: "integer", example: 2 },
      },
      ["orders", "total"],
    ),
    DeliveryOrderActionResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Delivery assigned successfully" },
        data: {
          type: "object",
          required: ["order"],
          properties: {
            order: ref("Order"),
          },
        },
      },
    },
    PaymentWebhookResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Webhook processed successfully" },
        data: {
          type: "object",
          required: ["order"],
          properties: {
            order: ref("Order"),
          },
        },
      },
    },
    NotificationListResponse: envelope(
      {
        notifications: { type: "array", items: ref("Notification") },
        page: { type: "integer", example: 1 },
        limit: { type: "integer", example: 20 },
      },
      ["notifications", "page", "limit"],
    ),
    NotificationUnreadResponse: envelope(
      {
        notifications: { type: "array", items: ref("Notification") },
      },
      ["notifications"],
    ),
    NotificationCountPayload: {
      type: "object",
      required: ["count"],
      properties: {
        count: { type: "integer", example: 7 },
      },
    },
    NotificationCountResponse: envelope({ count: ref("NotificationCountPayload") }, ["count"]),
    NotificationActionResponse: messageEnvelope("Notification marked as read"),
    ProductListResponse: {
      type: "object",
      required: ["status", "data"],
      properties: {
        status: { type: "string", example: "success" },
        data: {
          type: "object",
          required: ["products", "total", "page", "limit"],
          properties: {
            products: { type: "array", items: ref("Product") },
            total: { type: "integer", example: 24 },
            page: { type: "integer", example: 1 },
            limit: { type: "integer", example: 24 },
          },
        },
      },
    },
    ProductItemResponse: envelope({ product: ref("Product") }, ["product"]),
    StoreCreateRequest: {
      type: "object",
      required: ["name", "email"],
      properties: {
        name: { type: "string", example: "Downtown Market" },
        email: { type: "string", format: "email", example: "owner@example.com" },
        logo: { type: "string", example: "https://cdn.example.com/store/logo.png" },
        openingTime: { type: "string", example: "08:00", pattern: "^\\d{2}:\\d{2}$" },
        closingTime: { type: "string", example: "22:00", pattern: "^\\d{2}:\\d{2}$" },
        categoryId: oid("65f000000000000000002101"),
        categoryName: { type: "string", example: "Groceries" },
        authorizedBrand: { type: "string", example: "Apple" },
      },
    },
    StoreUpdateRequest: {
      type: "object",
      properties: {
        name: { type: "string", example: "Downtown Market" },
        logo: { type: "string", example: "https://cdn.example.com/store/logo.png" },
        isActive: { type: "boolean", example: true },
        openingTime: { type: "string", example: "08:00", pattern: "^\\d{2}:\\d{2}$" },
        closingTime: { type: "string", example: "22:00", pattern: "^\\d{2}:\\d{2}$" },
        categoryId: oid("65f000000000000000002102"),
        authorizedBrand: { type: "string", example: "Apple" },
      },
    },
    CategoryCreateRequest: {
      type: "object",
      required: ["name"],
      properties: {
        name: { type: "string", example: "Electronics" },
        parentId: oid("65f000000000000000002103"),
      },
    },
    CategoryUpdateRequest: {
      type: "object",
      properties: {
        name: { type: "string", example: "Mobiles" },
        parentId: oid("65f000000000000000002104"),
      },
    },
    CategoryReplaceRequest: {
      type: "object",
      required: ["replacementCategoryId"],
      properties: {
        replacementCategoryId: oid("65f000000000000000002105"),
        reason: { type: "string", maxLength: 500, example: "Consolidating duplicate taxonomy." },
      },
    },
    AuthRegisterRequest: {
      type: "object",
      required: ["name", "email", "password"],
      properties: {
        name: { type: "string", example: "Amina Hassan" },
        email: { type: "string", format: "email", example: "amina@example.com" },
        password: { type: "string", format: "password", example: "Str0ng!Pass" },
        phone: { type: "string", example: "01012345678" },
      },
    },
    AuthLoginRequest: {
      type: "object",
      required: ["email", "password"],
      properties: {
        email: { type: "string", format: "email", example: "amina@example.com" },
        password: { type: "string", format: "password", example: "Str0ng!Pass" },
      },
    },
    AuthForgotPasswordRequest: {
      type: "object",
      required: ["email"],
      properties: {
        email: { type: "string", format: "email", example: "amina@example.com" },
      },
    },
    AuthResetPasswordRequest: {
      type: "object",
      required: ["newPassword", "confirmPassword"],
      properties: {
        newPassword: { type: "string", format: "password", example: "N3w!Pass123" },
        confirmPassword: { type: "string", format: "password", example: "N3w!Pass123" },
      },
    },
    AuthSendCodeVerificationRequest: {
      type: "object",
      required: ["email"],
      properties: {
        email: { type: "string", format: "email", example: "amina@example.com" },
      },
    },
    AuthEmailVerificationRequest: {
      type: "object",
      required: ["email", "verifyCode"],
      properties: {
        email: { type: "string", format: "email", example: "amina@example.com" },
        verifyCode: { type: "string", example: "123456" },
      },
    },
    AuthRefreshResponse: {
      type: "object",
      required: ["status", "token", "data"],
      properties: {
        status: { type: "string", example: "success" },
        token: { type: "string", example: "eyJhbGciOiJIUzI1NiIs..." },
        data: { type: "object", required: ["user"], properties: { user: ref("AuthUser") } },
      },
    },
    CartAddItemRequest: {
      type: "object",
      required: ["variantId"],
      properties: {
        variantId: oid("65f000000000000000004101"),
        quantity: { type: "integer", minimum: 1, example: 2 },
      },
    },
    CartDecreaseItemRequest: {
      type: "object",
      properties: {
        quantity: { type: "integer", minimum: 1, example: 1 },
      },
    },
    WishlistAddItemRequest: {
      type: "object",
      required: ["variantId"],
      properties: {
        variantId: oid("65f000000000000000004102"),
      },
    },
    AddressCreateRequest: {
      type: "object",
      required: ["street", "city", "distanceMark", "phone"],
      properties: {
        street: { type: "string", example: "12 Tahrir Street" },
        city: { type: "string", example: "Cairo" },
        distanceMark: { type: "string", example: "Near the blue pharmacy" },
        phone: { type: "string", example: "01012345678" },
        notes: { type: "string", example: "Call before delivery." },
        isDefault: { type: "boolean", example: true },
      },
    },
    AddressUpdateRequest: {
      type: "object",
      properties: {
        street: { type: "string", example: "12 Tahrir Street" },
        city: { type: "string", example: "Cairo" },
        distanceMark: { type: "string", example: "Near the blue pharmacy" },
        phone: { type: "string", example: "01012345678" },
        notes: { type: "string", example: "Call before delivery." },
      },
    },
    AddressSetDefaultRequest: {
      type: "object",
      properties: {
        isDefault: { type: "boolean", example: true },
      },
    },
    OrderCreateRequest: {
      type: "object",
      required: ["addressId", "paymentMethod"],
      properties: {
        addressId: oid("65f000000000000000005101"),
        paymentMethod: ref("OrderPaymentMethod"),
      },
    },
    StoreOrderUpdateRequest: {
      type: "object",
      properties: {
        status: {
          type: "string",
          enum: ["pending", "preparing", "ready", "rejected"],
          example: "ready",
        },
        rejectionReason: { type: "string", example: "Item unavailable." },
        missingItems: {
          type: "array",
          items: {
            type: "object",
            required: ["orderItemId", "reason"],
            properties: {
              orderItemId: oid("65f000000000000000006101"),
              reason: { type: "string", example: "Variant out of stock." },
            },
          },
        },
      },
    },
    DeliveryAssignRequest: {
      type: "object",
      properties: {
        riderId: oid("65f000000000000000006201"),
      },
    },
    PaymentWebhookRequest: {
      type: "object",
      required: ["orderId", "event"],
      properties: {
        orderId: oid("65f000000000000000006202"),
        event: {
          type: "string",
          enum: ["payment.succeeded", "payment.failed", "payment.refunded"],
          example: "payment.succeeded",
        },
      },
    },
    StoreCreateResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Store created successfully" },
        data: {
          type: "object",
          required: ["store"],
          properties: {
            store: ref("Store"),
          },
        },
      },
    },
    StoreUpdateResponse: {
      type: "object",
      required: ["status", "message", "data"],
      properties: {
        status: { type: "string", example: "success" },
        message: { type: "string", example: "Store updated successfully" },
        data: {
          type: "object",
          required: ["store"],
          properties: {
            store: ref("Store"),
          },
        },
      },
    },
    StoreStatsResponse: {
      type: "object",
      required: ["status", "data"],
      properties: {
        status: { type: "string", example: "success" },
        data: ref("StoreDashboardStats"),
      },
    },
    StoreProductCreateRequest: {
      type: "object",
      required: ["name", "categoryId", "variants"],
      properties: {
        name: { type: "string", example: "iPhone 15 Pro Max" },
        slug: { type: "string", example: "iphone-15-pro-max" },
        description: { type: "string", example: "Flagship smartphone." },
        brand: { type: "string", example: "Apple" },
        categoryId: oid("65f000000000000000002201"),
        basePrice: { type: "number", minimum: 0, example: 44999 },
        variants: {
          type: "array",
          minItems: 1,
          items: ref("ProductVariant"),
        },
        defaultVariantId: oid("65f000000000000000003104"),
        images: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
      },
    },
    StoreProductUpdateRequest: {
      type: "object",
      properties: {
        name: { type: "string", example: "iPhone 15 Pro Max" },
        description: { type: "string", example: "Flagship smartphone." },
        brand: { type: "string", example: "Apple" },
        categoryId: oid("65f000000000000000002202"),
        basePrice: { type: "number", minimum: 0, example: 44999 },
        variants: {
          type: "array",
          items: ref("ProductVariant"),
        },
        addVariant: ref("ProductVariant"),
        defaultVariantId: oid("65f000000000000000003105"),
        images: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
        isActive: { type: "boolean", example: true },
      },
    },
  },
  requestBodies: {
    AuthRegisterRequest: requestBody("AuthRegisterRequest", "Create a new account."),
    AuthLoginRequest: requestBody("AuthLoginRequest", "Authenticate an existing account."),
    AuthForgotPasswordRequest: requestBody("AuthForgotPasswordRequest", "Start password reset flow."),
    AuthResetPasswordRequest: requestBody("AuthResetPasswordRequest", "Finalize password reset."),
    AuthSendCodeVerificationRequest: requestBody("AuthSendCodeVerificationRequest", "Send an email verification code."),
    AuthEmailVerificationRequest: requestBody("AuthEmailVerificationRequest", "Verify the email address with the code."),
    CategoryCreateRequest: requestBody("CategoryCreateRequest", "Create a category."),
    CategoryUpdateRequest: requestBody("CategoryUpdateRequest", "Update a category."),
    CategoryReplaceRequest: requestBody("CategoryReplaceRequest", "Replace a category with another category."),
    StoreCreateRequest: requestBody("StoreCreateRequest", "Create a store."),
    StoreUpdateRequest: requestBody("StoreUpdateRequest", "Update store settings."),
    StoreProductCreateRequest: requestBody("StoreProductCreateRequest", "Create a product inside a store."),
    StoreProductUpdateRequest: requestBody("StoreProductUpdateRequest", "Update a store product."),
    CartAddItemRequest: requestBody("CartAddItemRequest", "Add an item to the cart."),
    CartDecreaseItemRequest: requestBody("CartDecreaseItemRequest", "Decrease an item quantity."),
    WishlistAddItemRequest: requestBody("WishlistAddItemRequest", "Add an item to the wishlist."),
    AddressCreateRequest: requestBody("AddressCreateRequest", "Create a new delivery address."),
    AddressUpdateRequest: requestBody("AddressUpdateRequest", "Update an address."),
    AddressSetDefaultRequest: requestBody("AddressSetDefaultRequest", "Set or unset the default address flag."),
    OrderCreateRequest: requestBody("OrderCreateRequest", "Create an order."),
    StoreOrderUpdateRequest: requestBody("StoreOrderUpdateRequest", "Update store order status and rejection metadata."),
    DeliveryAssignRequest: requestBody("DeliveryAssignRequest", "Assign a rider to an order."),
    PaymentWebhookRequest: requestBody("PaymentWebhookRequest", "Payment gateway webhook payload."),
  },
  responses: {
    AuthSessionResponse: schemaResponse("AuthSessionEnvelope", "Authentication succeeded and an access token was issued."),
    AuthRefreshResponse: schemaResponse("AuthRefreshResponse", "Access token refreshed successfully."),
    AuthMessageResponse: schemaResponse("AuthMessageResponse", "Authentication action completed."),
    LogoutMessageResponse: stringResponse("Logout result.", "Logout successfully"),
    CategoryListResponse: schemaResponse("CategoryListResponse", "Categories fetched successfully."),
    CategoryItemResponse: schemaResponse("CategoryItemResponse", "Category fetched successfully."),
    CategoryActionResponse: schemaResponse("CategoryActionResponse", "Category mutated successfully."),
    CategoryUsageResponse: schemaResponse("CategoryUsageResponse", "Category usage statistics."),
    CategoryReplaceResponse: schemaResponse("CategoryReplaceResponse", "Category replacement processed successfully."),
    StoreListResponse: schemaResponse("StoreListResponse", "Stores fetched successfully."),
    StoreItemResponse: schemaResponse("StoreItemResponse", "Store fetched successfully."),
    StoreActionResponse: schemaResponse("StoreActionResponse", "Store updated successfully."),
    StoreCreateResponse: schemaResponse("StoreCreateResponse", "Store created successfully."),
    StoreUpdateResponse: schemaResponse("StoreUpdateResponse", "Store updated successfully."),
    StoreStatsResponse: schemaResponse("StoreStatsResponse", "Store dashboard statistics."),
    StoreProductListResponse: schemaResponse("StoreProductListResponse", "Store products fetched successfully."),
    StoreProductItemResponse: schemaResponse("StoreProductItemResponse", "Store product fetched successfully."),
    CartResponse: schemaResponse("CartResponse", "Cart fetched successfully."),
    CartActionResponse: schemaResponse("CartActionResponse", "Cart mutation completed successfully."),
    WishlistResponse: schemaResponse("WishlistResponse", "Wishlist fetched successfully."),
    WishlistActionResponse: schemaResponse("WishlistActionResponse", "Wishlist mutation completed successfully."),
    AddressListResponse: schemaResponse("AddressListResponse", "Addresses fetched successfully."),
    AddressItemResponse: schemaResponse("AddressItemResponse", "Address fetched successfully."),
    AddressActionResponse: schemaResponse("AddressActionResponse", "Address mutation completed successfully."),
    OrderListResponse: schemaResponse("OrderListResponse", "Orders fetched successfully."),
    OrderItemResponse: schemaResponse("OrderItemResponse", "Order fetched successfully."),
    OrderActionResponse: schemaResponse("OrderActionResponse", "Order mutation completed successfully."),
    StoreOrderListResponse: schemaResponse("StoreOrderListResponse", "Store orders fetched successfully."),
    StoreOrderItemResponse: schemaResponse("StoreOrderItemResponse", "Store order fetched successfully."),
    StoreOrderActionResponse: schemaResponse("StoreOrderActionResponse", "Store order mutation completed successfully."),
    DeliveryOrderListResponse: schemaResponse("DeliveryOrderListResponse", "Delivery orders fetched successfully."),
    DeliveryOrderActionResponse: schemaResponse("DeliveryOrderActionResponse", "Delivery order mutation completed successfully."),
    PaymentWebhookResponse: schemaResponse("PaymentWebhookResponse", "Payment webhook processed successfully."),
    NotificationListResponse: schemaResponse("NotificationListResponse", "Notifications fetched successfully."),
    NotificationUnreadResponse: schemaResponse("NotificationUnreadResponse", "Unread notifications fetched successfully."),
    NotificationCountResponse: schemaResponse("NotificationCountResponse", "Unread notification count fetched successfully."),
    NotificationActionResponse: schemaResponse("NotificationActionResponse", "Notification state changed successfully."),
    ProductListResponse: schemaResponse("ProductListResponse", "Products fetched successfully."),
    ProductItemResponse: schemaResponse("ProductItemResponse", "Product fetched successfully."),
    OrderPaymentPayload: schemaResponse("OrderPaymentPayload", "Payment intent created successfully."),
    PlainMessageResponse: schemaResponse("ApiMessage", "Action completed successfully."),
    BadRequestResponse: schemaResponse("ErrorResponse", "Bad request."),
    UnauthorizedResponse: schemaResponse("ErrorResponse", "Authentication is required or the token is invalid."),
    ForbiddenResponse: schemaResponse("ErrorResponse", "The authenticated user lacks permission for this route."),
    NotFoundResponse: schemaResponse("ErrorResponse", "Requested resource was not found."),
    ConflictResponse: schemaResponse("ErrorResponse", "Resource state conflict."),
    UnprocessableEntityResponse: schemaResponse("ErrorResponse", "Validation error."),
    InternalServerErrorResponse: schemaResponse("ErrorResponse", "Unexpected server error."),
  },
};

const commonErrors = (protectedRoute) => {
  const responses = {
    400: responseRef("BadRequestResponse"),
    404: responseRef("NotFoundResponse"),
    409: responseRef("ConflictResponse"),
    422: responseRef("UnprocessableEntityResponse"),
    500: responseRef("InternalServerErrorResponse"),
  };
  if (protectedRoute) {
    responses[401] = responseRef("UnauthorizedResponse");
    responses[403] = responseRef("ForbiddenResponse");
  }
  return responses;
};

const route = ({
  method,
  path,
  tag,
  operationId,
  summary,
  description,
  requestBody: body,
  params = [],
  responses: customResponses = {},
  security = [],
  protectedRoute = false,
  controller,
  middlewares = [],
  roles = [],
}) => {
  const op = {
    tags: [tag],
    summary,
    description,
    operationId,
    ...(params.length ? { parameters: params.map(paramRef) } : {}),
    ...(body ? { requestBody: requestRef(body) } : {}),
    ...(security.length ? { security } : {}),
    responses: {
      ...commonErrors(protectedRoute),
      ...customResponses,
    },
    ...(controller ? { "x-controller": controller } : {}),
    ...(middlewares.length ? { "x-middlewares": middlewares } : {}),
    ...(roles.length ? { "x-roles": roles } : {}),
  };

  return { method, path, op };
};

const routes = [
  route({
    method: "post",
    path: "/auth/register",
    tag: "Auth",
    operationId: "registerUser",
    summary: "Register a new user",
    description: "Public signup endpoint. Issues an access token and a refresh token cookie.",
    requestBody: "AuthRegisterRequest",
    responses: { 200: responseRef("AuthSessionResponse") },
    controller: "src/apis/auth/controllers/register.controller.ts",
    middlewares: ["validate(registerSchema)"],
  }),
  route({
    method: "post",
    path: "/auth/login",
    tag: "Auth",
    operationId: "loginUser",
    summary: "Login a user",
    description: "Public login endpoint. Issues an access token and a refresh token cookie.",
    requestBody: "AuthLoginRequest",
    responses: { 201: responseRef("AuthSessionResponse") },
    controller: "src/apis/auth/controllers/login.controller.ts",
    middlewares: ["validate(loginSchema)"],
  }),
  route({
    method: "post",
    path: "/auth/refresh",
    tag: "Auth",
    operationId: "refreshAccessToken",
    summary: "Refresh the access token",
    description: "Uses the refreshToken cookie to issue a new access token and refresh token cookie.",
    security: [{ RefreshTokenCookie: [] }],
    responses: { 200: responseRef("AuthRefreshResponse") },
    controller: "src/apis/auth/controllers/refresh.controller.ts",
    middlewares: ["refreshLimiter"],
  }),
  route({
    method: "get",
    path: "/auth/logout",
    tag: "Auth",
    operationId: "logoutUser",
    summary: "Logout the current session",
    description: "Clears the refresh token cookie and revokes the server-side refresh session.",
    security: [{ RefreshTokenCookie: [] }],
    responses: { 200: responseRef("LogoutMessageResponse") },
    controller: "src/apis/auth/controllers/logout.controller.ts",
  }),
  route({
    method: "post",
    path: "/auth/forgot-password",
    tag: "Auth",
    operationId: "forgotPassword",
    summary: "Start password reset flow",
    description: "Sends a reset email to the account owner.",
    requestBody: "AuthForgotPasswordRequest",
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/auth/controllers/forgot.controller.ts",
    middlewares: ["validate(forgotPasswordSchema)"],
  }),
  route({
    method: "post",
    path: "/auth/reset-password/{token}",
    tag: "Auth",
    operationId: "resetPassword",
    summary: "Complete password reset",
    description: "Uses the reset token from the URL path together with the new password payload.",
    params: ["TokenParam"],
    requestBody: "AuthResetPasswordRequest",
    responses: { 200: responseRef("AuthMessageResponse") },
    controller: "src/apis/auth/controllers/reset-password.controller.ts",
  }),
  route({
    method: "post",
    path: "/auth/send-code-email-verification",
    tag: "Auth",
    operationId: "sendEmailVerificationCode",
    summary: "Send email verification code",
    description: "Public endpoint that sends an email verification code to the supplied email address.",
    requestBody: "AuthSendCodeVerificationRequest",
    responses: { 200: responseRef("AuthMessageResponse") },
    controller: "src/apis/auth/controllers/email-send-code-verification.controller.ts",
  }),
  route({
    method: "patch",
    path: "/auth/email-verification",
    tag: "Auth",
    operationId: "verifyEmail",
    summary: "Verify email with code",
    description: "Public endpoint that validates the verification code for the supplied email address.",
    requestBody: "AuthEmailVerificationRequest",
    responses: { 200: responseRef("AuthMessageResponse") },
    controller: "src/apis/auth/controllers/email-verification.controller.ts",
  }),

  route({
    method: "get",
    path: "/categories",
    tag: "Categories",
    operationId: "listCategories",
    summary: "List categories",
    description: "Public endpoint that returns all categories ordered alphabetically.",
    responses: { 200: responseRef("CategoryListResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
  }),
  route({
    method: "get",
    path: "/categories/{categoryId}/usage",
    tag: "Categories",
    operationId: "getCategoryUsage",
    summary: "Get category usage",
    description: "Returns product and store usage for the category.",
    params: ["CategoryIdParam"],
    responses: { 200: responseRef("CategoryUsageResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
  }),
  route({
    method: "get",
    path: "/categories/{categoryId}",
    tag: "Categories",
    operationId: "getCategory",
    summary: "Get category by id",
    description: "Public endpoint that returns a single category record.",
    params: ["CategoryIdParam"],
    responses: { 200: responseRef("CategoryItemResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
  }),
  route({
    method: "post",
    path: "/categories",
    tag: "Categories",
    operationId: "createCategory",
    summary: "Create a category",
    description: "ADMIN only. Creates a category and optionally links it to a parent category.",
    requestBody: "CategoryCreateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 201: responseRef("CategoryActionResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)", "validate(createCategorySchema)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "patch",
    path: "/categories/{categoryId}",
    tag: "Categories",
    operationId: "updateCategory",
    summary: "Update a category",
    description: "ADMIN only. Updates the category name or parent category.",
    params: ["CategoryIdParam"],
    requestBody: "CategoryUpdateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CategoryActionResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)", "validate(updateCategorySchema)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "post",
    path: "/categories/{categoryId}/replace",
    tag: "Categories",
    operationId: "replaceCategory",
    summary: "Replace a category",
    description: "ADMIN only. Repoints downstream usage to another category and returns migration metadata.",
    params: ["CategoryIdParam"],
    requestBody: "CategoryReplaceRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CategoryReplaceResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)", "validate(replaceCategorySchema)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "delete",
    path: "/categories/{categoryId}",
    tag: "Categories",
    operationId: "deleteCategory",
    summary: "Delete a category",
    description: "ADMIN only. Rejects deletion when the category is still in use.",
    params: ["CategoryIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/category/controllers/category.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)"],
    roles: ["ADMIN"],
  }),

  route({
    method: "get",
    path: "/store",
    tag: "Stores",
    operationId: "listStores",
    summary: "List stores",
    description: "Public store listing. Admin users can use the active filter to include inactive stores.",
    params: ["ActiveParam"],
    responses: { 200: responseRef("StoreListResponse") },
    controller: "src/apis/store/controller/get-all-stores.controller.ts",
  }),
  route({
    method: "get",
    path: "/store/category/{categoryId}",
    tag: "Stores",
    operationId: "listStoresByCategory",
    summary: "List stores by category",
    description: "Public category-scoped store listing. Admin users can use the active filter to include inactive stores.",
    params: ["CategoryIdParam", "ActiveParam"],
    responses: { 200: responseRef("StoreListResponse") },
    controller: "src/apis/store/controller/get-stores-by-category.controller.ts",
  }),
  route({
    method: "get",
    path: "/store/admin",
    tag: "Stores",
    operationId: "listStoresAdmin",
    summary: "Admin store listing",
    description: "ADMIN only. Returns stores with owner details and supports the active filter.",
    params: ["ActiveParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreListResponse") },
    controller: "src/apis/store/controller/get-all-stores.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}",
    tag: "Stores",
    operationId: "getStoreById",
    summary: "Get store by id",
    description: "Public store details by store identifier.",
    params: ["StoreIdParam"],
    responses: { 200: responseRef("StoreItemResponse") },
    controller: "src/apis/store/controller/get-store-by-id.controller.ts",
  }),
  route({
    method: "get",
    path: "/store/{storeId}/products",
    tag: "Stores",
    operationId: "listStoreProductsPublic",
    summary: "List public products for a store",
    description: "Public store product listing with search, paging, and activity filters.",
    params: ["StoreIdParam", "SearchParam", "PageParam", "LimitParam", "IsActiveParam"],
    responses: { 200: responseRef("StoreProductListResponse") },
    controller: "src/apis/store/products/controllers/list-store-products-public.controller.ts",
    middlewares: ["query validation in controller"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/products/{productId}",
    tag: "Stores",
    operationId: "getStoreProductPublic",
    summary: "Get a public store product",
    description: "Public product detail lookup within a specific store.",
    params: ["StoreIdParam", "ProductIdParam"],
    responses: { 200: responseRef("StoreProductItemResponse") },
    controller: "src/apis/store/products/controllers/get-store-product-public.controller.ts",
  }),
  route({
    method: "post",
    path: "/store",
    tag: "Stores",
    operationId: "createStore",
    summary: "Create a store",
    description: "ADMIN only. Creates a store and requires either categoryId or categoryName.",
    requestBody: "StoreCreateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 201: responseRef("StoreCreateResponse") },
    controller: "src/apis/store/controller/create-store.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)", "validate(createStoreSchema)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/my-store",
    tag: "Store Management",
    operationId: "getMyStoreByOwner",
    summary: "Get the current owner's store",
    description: "OWNER or ADMIN only. Returns the store owned by the authenticated user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreItemResponse") },
    controller: "src/apis/store/controller/get-my-store-by-owner.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/store/{storeId}/manage/settings",
    tag: "Store Management",
    operationId: "updateMyStore",
    summary: "Update store settings",
    description: "OWNER or ADMIN only. Updates store settings for a store owned by the authenticated user.",
    params: ["StoreIdParam"],
    requestBody: "StoreUpdateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreUpdateResponse") },
    controller: "src/apis/store/controller/update-store.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/manage/dashboard",
    tag: "Store Management",
    operationId: "getStoreDashboard",
    summary: "Get store dashboard metrics",
    description: "OWNER or ADMIN only. Returns sales and product engagement statistics for the store.",
    params: ["StoreIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreStatsResponse") },
    controller: "src/apis/store/controller/dashboard.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "delete",
    path: "/store/{storeId}/manage/delete",
    tag: "Store Management",
    operationId: "hardDeleteStore",
    summary: "Hard delete a store",
    description: "ADMIN only. Permanently deletes a store.",
    params: ["StoreIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/store/controller/delete-store.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.ADMIN)"],
    roles: ["ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/manage/products",
    tag: "Store Products",
    operationId: "listMyStoreProducts",
    summary: "List store products",
    description: "OWNER or ADMIN only. Returns all products for the requested store with paging and search.",
    params: ["StoreIdParam", "SearchParam", "PageParam", "LimitParam", "IsActiveParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreProductListResponse") },
    controller: "src/apis/store/products/controllers/list-my-store-products.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/manage/products/{productId}",
    tag: "Store Products",
    operationId: "getMyStoreProduct",
    summary: "Get a store product",
    description: "OWNER or ADMIN only. Returns a single store-owned product.",
    params: ["StoreIdParam", "ProductIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreProductItemResponse") },
    controller: "src/apis/store/products/controllers/get-my-store-product.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "post",
    path: "/store/{storeId}/manage/products",
    tag: "Store Products",
    operationId: "createStoreProduct",
    summary: "Create a store product",
    description: "OWNER or ADMIN only. Creates a product for the specified store.",
    params: ["StoreIdParam"],
    requestBody: "StoreProductCreateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 201: responseRef("StoreProductItemResponse") },
    controller: "src/apis/store/products/controllers/create-store-product.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)", "validate(createStoreProductSchema)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/store/{storeId}/manage/products/{productId}",
    tag: "Store Products",
    operationId: "updateStoreProduct",
    summary: "Update a store product",
    description: "OWNER or ADMIN only. Updates an existing store product.",
    params: ["StoreIdParam", "ProductIdParam"],
    requestBody: "StoreProductUpdateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreProductItemResponse") },
    controller: "src/apis/store/products/controllers/update-my-store-product.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)", "validate(updateStoreProductSchema)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "delete",
    path: "/store/{storeId}/manage/products/{productId}",
    tag: "Store Products",
    operationId: "deleteStoreProduct",
    summary: "Delete a store product",
    description: "OWNER or ADMIN only. Deletes a product from the store.",
    params: ["StoreIdParam", "ProductIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/store/products/controllers/delete-my-store-product.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/manage/orders",
    tag: "Store Management",
    operationId: "listStoreOrders",
    summary: "List store orders",
    description: "OWNER or ADMIN only. Returns orders for the store in a store-scoped view.",
    params: ["StoreIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreOrderListResponse") },
    controller: "src/apis/store/controller/get-my-orders.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "get",
    path: "/store/{storeId}/manage/orders/{orderId}",
    tag: "Store Management",
    operationId: "getStoreOrder",
    summary: "Get a store order",
    description: "OWNER or ADMIN only. Returns a single store-scoped order view.",
    params: ["StoreIdParam", "OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreOrderItemResponse") },
    controller: "src/apis/store/controller/get-my-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)"],
    roles: ["OWNER", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/store/{storeId}/manage/orders/{orderId}",
    tag: "Store Management",
    operationId: "updateStoreOrder",
    summary: "Update a store order",
    description: "OWNER or ADMIN only. Updates store order state, status, and missing-item metadata.",
    params: ["StoreIdParam", "OrderIdParam"],
    requestBody: "StoreOrderUpdateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("StoreOrderActionResponse") },
    controller: "src/apis/store/controller/update-my-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.OWNER, Role.ADMIN)", "validate(updateStoreOrderSchema)"],
    roles: ["OWNER", "ADMIN"],
  }),

  route({
    method: "get",
    path: "/products",
    tag: "Catalog",
    operationId: "listProducts",
    summary: "List catalog products",
    description: "Public product browsing endpoint with paging, filtering, sorting, and attribute filtering.",
    params: ["StoreQueryParam", "ShopIdParam", "CategoryQueryParam", "SearchParam", "MinPriceParam", "MaxPriceParam", "SortParam", "PageParam", "LimitParam", "ColorParam", "SizeParam"],
    responses: { 200: responseRef("ProductListResponse") },
    controller: "src/apis/products-and-variants/controllers/list-products.controller.ts",
    middlewares: ["query validation in controller"],
  }),
  route({
    method: "get",
    path: "/products/{slug}",
    tag: "Catalog",
    operationId: "getProductBySlug",
    summary: "Get product by slug",
    description: "Public product lookup by slug. Optionally accepts storeId to disambiguate between stores.",
    params: ["SlugParam", "StoreQueryParam"],
    responses: { 200: responseRef("ProductItemResponse") },
    controller: "src/apis/products-and-variants/controllers/get-product-by-slug.controller.ts",
  }),

  route({
    method: "get",
    path: "/cart",
    tag: "Cart",
    operationId: "getCart",
    summary: "Get the current user's cart",
    description: "Authenticated cart retrieval for the current user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CartResponse") },
    controller: "src/apis/cart/controllers/get-cart.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "post",
    path: "/cart/item",
    tag: "Cart",
    operationId: "addCartItem",
    summary: "Add item to cart",
    description: "Authenticated cart mutation for the current user.",
    requestBody: "CartAddItemRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CartActionResponse") },
    controller: "src/apis/cart/controllers/add-cart-item.controller.ts",
    middlewares: ["authorized", "validate(addCartItemSchema)"],
  }),
  route({
    method: "patch",
    path: "/cart/items/{variantId}/decrease",
    tag: "Cart",
    operationId: "decreaseCartItem",
    summary: "Decrease cart item quantity",
    description: "Authenticated cart mutation for the current user.",
    params: ["VariantIdParam"],
    requestBody: "CartDecreaseItemRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CartActionResponse") },
    controller: "src/apis/cart/controllers/decrease-cart-item.controller.ts",
    middlewares: ["authorized", "validate(decreaseCartItemSchema)"],
  }),
  route({
    method: "delete",
    path: "/cart/item/{variantId}",
    tag: "Cart",
    operationId: "removeCartItem",
    summary: "Remove item from cart",
    description: "Authenticated cart mutation for the current user.",
    params: ["VariantIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CartActionResponse") },
    controller: "src/apis/cart/controllers/remove-cart-item.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "delete",
    path: "/cart",
    tag: "Cart",
    operationId: "clearCart",
    summary: "Clear the cart",
    description: "Authenticated cart mutation for the current user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("CartActionResponse") },
    controller: "src/apis/cart/controllers/clear-cart.controller.ts",
    middlewares: ["authorized"],
  }),

  route({
    method: "get",
    path: "/wishlist",
    tag: "Wishlist",
    operationId: "getWishList",
    summary: "Get the current user's wishlist",
    description: "Authenticated wishlist retrieval for the current user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("WishlistResponse") },
    controller: "src/apis/wish-list/controllers/get-wishlist.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "post",
    path: "/wishlist/item",
    tag: "Wishlist",
    operationId: "addWishListItem",
    summary: "Add item to wishlist",
    description: "Authenticated wishlist mutation for the current user.",
    requestBody: "WishlistAddItemRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("WishlistActionResponse") },
    controller: "src/apis/wish-list/controllers/add-wishlist-item.controller.ts",
    middlewares: ["authorized", "validate(addSchema)"],
  }),
  route({
    method: "delete",
    path: "/wishlist/item/{variantId}",
    tag: "Wishlist",
    operationId: "removeWishListItem",
    summary: "Remove item from wishlist",
    description: "Authenticated wishlist mutation for the current user.",
    params: ["VariantIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("WishlistActionResponse") },
    controller: "src/apis/wish-list/controllers/remove-wishlist.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "delete",
    path: "/wishlist",
    tag: "Wishlist",
    operationId: "clearWishList",
    summary: "Clear the wishlist",
    description: "Authenticated wishlist mutation for the current user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("WishlistActionResponse") },
    controller: "src/apis/wish-list/controllers/clear-wishlist.controller.ts",
    middlewares: ["authorized"],
  }),

  route({
    method: "get",
    path: "/addresses",
    tag: "Addresses",
    operationId: "getMyAddresses",
    summary: "List addresses",
    description: "Authenticated address book retrieval.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("AddressListResponse") },
    controller: "src/apis/address/controllers/get-my-addresses.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "get",
    path: "/addresses/default",
    tag: "Addresses",
    operationId: "getDefaultAddress",
    summary: "Get default address",
    description: "Authenticated retrieval of the current default address.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("AddressItemResponse") },
    controller: "src/apis/address/controllers/get-default-address.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "get",
    path: "/addresses/{addressId}",
    tag: "Addresses",
    operationId: "getAddressById",
    summary: "Get an address by id",
    description: "Authenticated retrieval of a specific address owned by the current user.",
    params: ["AddressIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("AddressItemResponse") },
    controller: "src/apis/address/controllers/get-address-by-id.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "post",
    path: "/addresses",
    tag: "Addresses",
    operationId: "createAddress",
    summary: "Create an address",
    description: "Authenticated creation of a new address.",
    requestBody: "AddressCreateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 201: responseRef("AddressItemResponse") },
    controller: "src/apis/address/controllers/create-address.controller.ts",
    middlewares: ["authorized", "validate(createAddressSchema)"],
  }),
  route({
    method: "patch",
    path: "/addresses/{addressId}",
    tag: "Addresses",
    operationId: "updateAddress",
    summary: "Update an address",
    description: "Authenticated update of a specific address owned by the current user.",
    params: ["AddressIdParam"],
    requestBody: "AddressUpdateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("AddressItemResponse") },
    controller: "src/apis/address/controllers/update-address.controller.ts",
    middlewares: ["authorized", "validate(updateAddressSchema)"],
  }),
  route({
    method: "patch",
    path: "/addresses/{addressId}/default",
    tag: "Addresses",
    operationId: "setDefaultAddress",
    summary: "Set default address",
    description: "Authenticated default-address mutation for a specific address.",
    params: ["AddressIdParam"],
    requestBody: "AddressSetDefaultRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("AddressItemResponse") },
    controller: "src/apis/address/controllers/set-default-address.controller.ts",
    middlewares: ["authorized", "validate(setDefaultAddressSchema)"],
  }),
  route({
    method: "delete",
    path: "/addresses/{addressId}",
    tag: "Addresses",
    operationId: "deleteAddress",
    summary: "Delete an address",
    description: "Authenticated deletion of a specific address owned by the current user.",
    params: ["AddressIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/address/controllers/delete-address.controller.ts",
    middlewares: ["authorized"],
  }),

  route({
    method: "get",
    path: "/orders",
    tag: "Orders",
    operationId: "getUserOrders",
    summary: "List the current user's orders",
    description: "Authenticated user order history.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("OrderListResponse") },
    controller: "src/apis/order/controllers/get-user-orders.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "get",
    path: "/orders/{orderId}",
    tag: "Orders",
    operationId: "getUserOrder",
    summary: "Get a user order",
    description: "Authenticated order lookup for the current user.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("OrderItemResponse") },
    controller: "src/apis/order/controllers/get-user-order.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "post",
    path: "/orders",
    tag: "Orders",
    operationId: "createOrder",
    summary: "Create an order",
    description: "Authenticated order creation using a saved address and payment method.",
    requestBody: "OrderCreateRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 201: responseRef("OrderActionResponse") },
    controller: "src/apis/order/controllers/create-order.controller.ts",
    middlewares: ["authorized", "validate(createOrderSchema)"],
  }),
  route({
    method: "patch",
    path: "/orders/{orderId}/accept-partial",
    tag: "Orders",
    operationId: "acceptPartialOrder",
    summary: "Accept a partial order",
    description: "Authenticated order mutation for the current user.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("OrderActionResponse") },
    controller: "src/apis/order/controllers/accept-partial-order.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "patch",
    path: "/orders/{orderId}/cancel",
    tag: "Orders",
    operationId: "cancelOrder",
    summary: "Cancel an order",
    description: "Authenticated order mutation for the current user.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("OrderActionResponse") },
    controller: "src/apis/order/controllers/cancel-order.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "post",
    path: "/orders/{orderId}/pay",
    tag: "Orders",
    operationId: "createPaymentIntent",
    summary: "Create a payment intent",
    description: "Authenticated online-payment flow for the current user's order.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("OrderPaymentPayload") },
    controller: "src/apis/order/controllers/create-payment-intent.controller.ts",
    middlewares: ["authorized"],
  }),

  route({
    method: "get",
    path: "/delivery/orders",
    tag: "Delivery",
    operationId: "getDeliveryOrders",
    summary: "List delivery orders",
    description: "FULFILLMENT or ADMIN only. Returns orders available to the delivery workflow.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("DeliveryOrderListResponse") },
    controller: "src/apis/order/controllers/get-delivery-orders.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.FULFILLMENT, Role.ADMIN)"],
    roles: ["FULFILLMENT", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/delivery/orders/{orderId}/assign",
    tag: "Delivery",
    operationId: "assignDeliveryOrder",
    summary: "Assign a rider to an order",
    description: "FULFILLMENT or ADMIN only. Assigns a rider to a delivery order.",
    params: ["OrderIdParam"],
    requestBody: "DeliveryAssignRequest",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("DeliveryOrderActionResponse") },
    controller: "src/apis/order/controllers/assign-delivery-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.FULFILLMENT, Role.ADMIN)", "validate(assignDeliverySchema)"],
    roles: ["FULFILLMENT", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/delivery/orders/{orderId}/collect",
    tag: "Delivery",
    operationId: "collectDeliveryOrder",
    summary: "Start collecting an order",
    description: "FULFILLMENT or ADMIN only. Marks the order as being collected.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("DeliveryOrderActionResponse") },
    controller: "src/apis/order/controllers/collect-delivery-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.FULFILLMENT, Role.ADMIN)"],
    roles: ["FULFILLMENT", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/delivery/orders/{orderId}/start",
    tag: "Delivery",
    operationId: "startDeliveryOrder",
    summary: "Start delivery",
    description: "FULFILLMENT or ADMIN only. Marks the order as on the way.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("DeliveryOrderActionResponse") },
    controller: "src/apis/order/controllers/start-delivery-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.FULFILLMENT, Role.ADMIN)"],
    roles: ["FULFILLMENT", "ADMIN"],
  }),
  route({
    method: "patch",
    path: "/delivery/orders/{orderId}/deliver",
    tag: "Delivery",
    operationId: "deliverDeliveryOrder",
    summary: "Complete delivery",
    description: "FULFILLMENT or ADMIN only. Marks the order as delivered.",
    params: ["OrderIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("DeliveryOrderActionResponse") },
    controller: "src/apis/order/controllers/deliver-delivery-order.controller.ts",
    middlewares: ["authorized", "isAuthorized(Role.FULFILLMENT, Role.ADMIN)"],
    roles: ["FULFILLMENT", "ADMIN"],
  }),

  route({
    method: "post",
    path: "/payments/webhook",
    tag: "Payments",
    operationId: "paymentWebhook",
    summary: "Payment webhook",
    description: "Webhook endpoint used by the payment provider to update order payment state.",
    requestBody: "PaymentWebhookRequest",
    responses: { 200: responseRef("PaymentWebhookResponse") },
    controller: "src/apis/order/controllers/payment-webhook.controller.ts",
    middlewares: ["validate(paymentWebhookSchema)"],
  }),

  route({
    method: "get",
    path: "/notifications",
    tag: "Notifications",
    operationId: "getNotifications",
    summary: "List notifications",
    description: "Authenticated paginated notification listing.",
    params: ["PageParam", "LimitParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("NotificationListResponse") },
    controller: "src/apis/notifications/controllers/get-notifications.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "get",
    path: "/notifications/unread",
    tag: "Notifications",
    operationId: "getUnreadNotifications",
    summary: "List unread notifications",
    description: "Authenticated unread notification listing.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("NotificationUnreadResponse") },
    controller: "src/apis/notifications/controllers/get-unread-notifications.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "get",
    path: "/notifications/unread-count",
    tag: "Notifications",
    operationId: "getUnreadNotificationCount",
    summary: "Count unread notifications",
    description: "Authenticated unread notification count endpoint.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("NotificationCountResponse") },
    controller: "src/apis/notifications/controllers/get-unread-count.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "patch",
    path: "/notifications/{notificationId}/read",
    tag: "Notifications",
    operationId: "markNotificationRead",
    summary: "Mark a notification as read",
    description: "Authenticated notification mutation for the current user.",
    params: ["NotificationIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("NotificationActionResponse") },
    controller: "src/apis/notifications/controllers/mark-notification-read.controller.ts",
    middlewares: ["authorized", "validate(notificationIdParamsSchema)"],
  }),
  route({
    method: "patch",
    path: "/notifications/read-all",
    tag: "Notifications",
    operationId: "markAllNotificationsRead",
    summary: "Mark all notifications as read",
    description: "Authenticated notification mutation for the current user.",
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("NotificationActionResponse") },
    controller: "src/apis/notifications/controllers/mark-all-notifications-read.controller.ts",
    middlewares: ["authorized"],
  }),
  route({
    method: "delete",
    path: "/notifications/{notificationId}",
    tag: "Notifications",
    operationId: "deleteNotification",
    summary: "Delete a notification",
    description: "Authenticated notification mutation for the current user.",
    params: ["NotificationIdParam"],
    security: [{ BearerAuth: [] }],
    protectedRoute: true,
    responses: { 200: responseRef("PlainMessageResponse") },
    controller: "src/apis/notifications/controllers/delete-notification.controller.ts",
    middlewares: ["authorized", "validate(notificationIdParamsSchema)"],
  }),
];

const paths = {};
for (const item of routes) {
  if (!paths[item.path]) {
    paths[item.path] = {};
  }
  paths[item.path][item.method] = item.op;
}

const spec = {
  openapi: "3.1.0",
  info: {
    title: "E-Mall API",
    version: "1.0.0",
    description:
      "Production-grade OpenAPI documentation for the E-Mall Node.js, Express, TypeScript, and MongoDB backend.",
    contact: {
      name: "E-Mall API Support",
      email: "support@example.com",
    },
    license: {
      name: "ISC",
    },
  },
  servers: [
    {
      url: "http://localhost:4000",
      description: "Local development server",
    },
    {
      url: "https://api.example.com",
      description: "Production server placeholder",
    },
  ],
  tags,
  paths,
  components,
};

fs.writeFileSync(sourcePath, JSON.stringify(spec, null, 2));
fs.writeFileSync(outputPath, JSON.stringify(spec, null, 2));
console.log(`OpenAPI spec written to ${sourcePath} and ${outputPath}`);
